server:
    # context-path: /myboot 
    session-timeout: 1800
    tomcat:
        max-threads: 2000
        max-connections: 2000
#        min-spare-threads: 30
    port: 6008
#    uri-encoding: utf-8
security:
  basic:
    enabled: false
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: dev
  http:

  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
mybatis: 
  configuration:
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.cnce.**.domain
#配置缓存和session存储方式，默认ehcache,可选redis
cacheType: ehcache

#链接信息缓存时间
conn.duration.sec: 180
socket.port: 6001
socket.log: false
check.sum: false
super.user: admin